Milestone 1: Unit test for Add and delete function
Rachelwebdev/Interactive-to-do-list-with-webpack-bundle pull request #6
Opened 2023-01-26 10:16 UTC by Rachelwebdev

### In this milestone, we:
- Installed Jest Framework for testing
- Created a test file containing two tests for add and delete item functions
- Used Mocks to manipulate the DOM and imitate the local storage.
- Used the describe method to group tests
- Fixed linter errors

2023-01-26 10:44 UTC, Munsa1 requested changes
Hi @Rachelwebdev  @Lancelot-SO, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-26 10:44 UTC, Munsa1 commented on src/modules/listCard.js
>    tasksArray.forEach((toDo) => {
- [ ] One test is failing, kindly fix this failing test as this is a requirement.
![image](https://user-images.githubusercontent.com/81932478/214816570-da8b5c7e-5731-4113-9878-b30e25209ca0.png)

2023-01-26 14:18 UTC, Abenezer-Tilahun commented on src/modules/listCard.js
>    tasksArray.forEach((toDo) => {
Fixed.

2023-01-26 14:20 UTC, Abenezer-Tilahun approved these changes
Hi @Rachelwebdev   @Lancelot-SO 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git -Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ All Test Are Passing.
✔️ Good job for Implemented Suggested changes.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-26 15:01 UTC, merged

2023-02-24 13:36 UTC, Rachelwebdev commented
Thanks for the approval 👍